# Generated by Django 5.0 on 2023-12-08 19:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('categoria', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Anuncio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor', models.CharField(max_length=10)),
                ('estado', models.CharField(max_length=2)),
                ('cidade', models.CharField(max_length=20)),
                ('rua', models.CharField(max_length=50)),
                ('numero', models.CharField(max_length=4)),
                ('quantidade_banheiro', models.CharField(max_length=3)),
                ('quantidade_quartos', models.CharField(max_length=3)),
                ('area_terreno', models.CharField(max_length=8)),
                ('andares', models.CharField(max_length=3)),
                ('garagens', models.CharField(max_length=3)),
                ('img', models.ImageField(upload_to='img/%Y/%m/%h')),
                ('telefone_anunciante', models.CharField(max_length=30)),
                ('email_anunciante', models.EmailField(max_length=60)),
                ('categoria_anuncio', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='categoria.categoria')),
                ('usuario_anuncio', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
